package com.scoringapps.molkkyparty;

import java.io.IOException;
import java.util.List;

import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import com.googlecode.objectify.Key;
import com.googlecode.objectify.Objectify;
import com.googlecode.objectify.ObjectifyService;
import com.scoringapps.molkkyparty.api.AbstractEndPoint;
import com.scoringapps.molkkyparty.entity.User;

@SuppressWarnings("serial")
public class MolkkyPartyServlet extends HttpServlet {
	public void doGet(HttpServletRequest req, HttpServletResponse resp) throws IOException {

		Objectify ofy = ObjectifyService.begin();

		List<User> users = AbstractEndPoint.userDao.getAll();
		for (User u : users) {
			resp.getWriter().println("id:" + u.id + " // " + u.name + " - " + u.email);
		}

		// Simple create
		User user1 = new User();
		user1.login = "JLE";
		user1.name = "Julien";
		user1.email = "jle@test.com";
		AbstractEndPoint.userDao.save(user1);
		assert user1.id != null; // id was autogenerated

		// Get it back
		User fetched1 = ofy.get(new Key<User>(User.class, user1.id));
		User fetched2 = ofy.get(User.class, user1.id); // equivalent,
														// more
		// convenient
		// assert ar)eEqual(user1, fetched1, fetched2);

		// Change some data and write it
		user1.email = "jle2@test.com";
		ofy.put(user1);

		resp.setContentType("text/plain");
		resp.getWriter().println("Hello, world");
		resp.getWriter().println("<br>name:" + user1.name);
		resp.getWriter().println("<br>email:" + user1.email);
	}
}
